package ru.yandex.practicum.filmorate.exception;

public enum ExceptionType {
    INVALID_LOGIN,
    USER_NOT_FOUND,
    FILM_NOT_FOUND,
    GENRE_NOT_FOUND,
    MPA_NOT_FOUND,
    INVALID_FILM_RELEASE_DATE,
    INVALID_FILM_DESCRIPTION,
    USER_LIKE_ALREADY_EXISTS,
    USER_LIKE_NOT_EXISTS,
    INVALID_FRIENDSHIP_ADD,
    INVALID_FRIENDSHIP_REMOVE,
    UNEXPECTED_ERROR
}
